---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-ms
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-ms
  template:
    metadata:
      labels:
        app: stock-ms
    spec:
      containers:
      - name: stock-ms
        image: bennma2000/stockms:latest
        ports:
        - containerPort: 8080
